### ISSUE TITLE
install command in documentation doesn't work

### ISSUE THREAD

**Issue by roberto-proenca** [Alloyed/lua-lsp#19]
I tried installing following the instructions:
`$ luarocks install --from=http://luarocks.org/dev lua-lsp`

but i received an error:
`Error: No results matching query were found.`

it only found the download with:
`$ luarocks install --from=http://luarocks.org/dev lua-lsp`

**Comment by Alloyed** [comment]
I uh, don't see the difference between the two? I'll go test it right now
yeah it worked for me: maybe we have different versions of luarocks installed or something?

**Comment by ThaisRobba** [comment]
Seems like Luarocks 2.0 (standard with LuaForWindows) doesn't work with that command.

**Comment by Stanzilla** [comment]
LuaForWindows is pretty outdated though

**Comment by ThaisRobba** [comment]
Aye - it would probably warrant a note or something in the README.md as it is still one of the most common ways to install Luarocks on Windows.

**Comment by Alloyed** [comment]
feel free to reopen if you are still having issues~
