### ISSUE TITLE
Error installing.

### ISSUE THREAD

**Issue by hifall** [Alloyed/lua-lsp#20]
I am having this issue on Ubuntu 16.04.

When I run this:
`./luarocks install --server=http://luarocks.org/dev lua-lsp`
I get:
`Error: Failed finding Lua header files. You may need to install them or configure LUA_INCDIR.`

At that point of time, Lua has already been installed, and LUA_INCDIR env var has been set to Lua's src directory which contains the headers.

Any idea?

**Comment by karai17** [comment]
You need to install the lua dev files. In Ubuntu it should be called `liblua-dev` or something similar.

**Comment by Alloyed** [comment]
feel free to reopen if you are still having issues~
