### ISSUE TITLE
Goto definition is not working on field methods

### ISSUE THREAD

**Issue by pyericz** [Alloyed/lua-lsp#25]
I'm using [neoclide/coc.nvim](https://github.com/neoclide/coc.nvim) as language client support in my vim editor. However, when I move the cursor to `self:foo()` inside the `module:bar()` function, and try `gd` key, which is mapped to `<Plug>(coc-definition)`, it will output the error about finding no definition. 
```lua 
local module = {}

function module:foo()
end

function module:bar()
    self:foo()
end
```

**Comment by Alloyed** [comment]
yep, tracked as #14. Right now there isn't a special case for self, but it would definitely be handy to assume that the first parameter of a method call is an object that looks like setmetatable({}, {__index = module}) and follow references/track mutations accordingly

**Comment by Alloyed** [comment]
duplicate
