### ISSUE TITLE
 accept more recent lpeglabel

### ISSUE THREAD

**Issue by teto** [Alloyed/lua-lsp#28]
hi,

Thanks for the nice package. Would be nice to accept more recent lpeglabel to prevent this:
```
-- Performing Test HAS_DIAG_COLOR_FLAG - Success
-- Found PkgConfig: /nix/store/50vxsm7w48l5mqa2f114c43vcyyixxn0-pkg-config-0.29.2/bin/pkg-config (found version "0.29.2")
Missing dependencies for lua-lsp scm-2:
   lpeglabel ~> 1.5 (1.6.0-1 installed)

lua-lsp scm-2 depends on lpeglabel ~> 1.5 (1.6.0-1 installed)
```
Also I package this program for nixos and it would be cool to have:
- a rock available as well on luarocks.org
- fill the rockspec description instead of `"No summary";`

**Comment by Alloyed** [comment]
new rockspec uploaded with a summary and updated dependencies.
I'd like to publish a rock as well, but first it's probably prudent to tag a release and package that instead of just packaging whatever.

**Comment by teto** [comment]
thanks !
