### ISSUE TITLE
I Meet A ERROR When Start LU-LSP.BAT

### ISSUE THREAD

**Issue by gVimer** [Alloyed/lua-lsp#30]
ensions/coc-lua-data/tools/share/lua/5.3/lua-lsp\rpc.lua:111: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...ensions/coc-lua-data/tools/share/lua/5.3/lua-lsp\rpc.lua:111: in function 'lua-lsp.rpc.decode'
        ...nsions/coc-lua-data/tools/share/lua/5.3/lua-lsp\loop.lua:35: in function 'lua-lsp.loop'
        ...a\tools\lib\luarocks\rocks-5.3\lua-lsp\scm-2\bin\lua-lsp:3: in main chunk
        [C]: in ?
How To Solve It？

**Comment by vadi2** [comment]
How did you solve it?

**Comment by gVimer** [comment]
> How did you solve it?

There is a bug in Win。In the file coc\extensions\node_modules\coc-lua\lib\utils\tools.js Change line 21 : return path_1.default.join(yield config_1.configDir('tools', 'bin'), 'lua-lsp')  TO
  return path_1.default.join(yield config_1.configDir('tools', 'bin'), 'lua-lsp.bat')  and It's OK 
I think you should be able to understand what I mean!!!
