### ISSUE TITLE
Update LuaRocks Package

### ISSUE THREAD

**Issue by qbsc** [Alloyed/lua-lsp#33]
The [package over on luarocks.org](https://luarocks.org/modules/alloyed/lua-lsp) is 2 years old, and there have definitely been commits since then. The version there is still missing the rockspec update to include the missing formatting module, so formatting is broken, which is how I noticed.

Sooooo publish master to luarocks.org, please?

**Comment by Alloyed** [comment]
it's likely that the old package was valid, but for other reasons I've merged dev into master and updated the package anyways. Formatting exists, but it is only optionally enabled:
```
$ luarocks-5.1 install Formatter
$ luarocks-5.3 install lcf
```
to pick the flavor of formatter you prefer.
closing for age but if you're still using lua-lsp and are still having an issue you're more than welcome to reopen~
