### ISSUE TITLE
fill missing using package manager luarocks

### ISSUE THREAD

**Issue by ioperations** [Alloyed/lua-lsp#38]
file lua-lsp/json.lua actually not installed via command `luarocks install --server=http://luarocks.org/dev lua-lsp` ;

2020-10-21

$tree 
 tree
.
├── analyze.lua
├── data
│   ├── 5_1.lua
│   ├── 5_2.lua
│   ├── 5_3.lua
│   ├── love-completions.lua
│   ├── luajit-2_0.lua
│   └── _test.lua
├── formatting.lua
├── log.lua
├── loop.lua
├── lua-parser
│   ├── parser.lua
│   ├── scope.lua
│   └── validator.lua
├── methods.lua
├── rpc.lua
└── unicode.lua

2 directories, 16 files

**Comment by Alloyed** [comment]
yep, should be fixed by scm-5 and 0.1.0-2, let me know if something else is wrong~
